### ISSUE TITLE
Failed resolution of: Lokhttp3/internal/http/HttpEngine

### ISSUE THREAD

**Issue by alirezat775** [charbgr/SeismicInterceptor#1]
Hi, I have a problem in using this library
After shaking when click on item (request) app crashed!
`    java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/internal/http/HttpEngine;
`
can you please check check it?
 `
 Caused by: java.lang.ClassNotFoundException: Didn't find class "okhttp3.internal.http.HttpEngine" on path: DexPathList
`

I guess crash is from okhttp version

**Comment by charbgr** [comment]
Do you have a repro project to see in detail?

**Comment by alirezat775** [comment]
relay project is private but i tried implemented in [https://github.com/alirezat775/Quotes](project)

**Comment by charbgr** [comment]
I don't find any branch :/

Can you force the version of SeismicInterceptor's OkHttp?

**Comment by alirezat775** [comment]
No, I just implemented a library from a document.
I pushed again in https://github.com/alirezat775/Quotes/tree/seismicinterceptor

**Comment by alirezat775** [comment]
Hi @charbgr, have any update about this issue?

**Comment by charbgr** [comment]
Didn't find time to address the issue :( maybe tomorrow or Monday.

Did you try to force resolution strategy throught gradle? I see that seismicinterceptor and quotes have different OkHttp versions

**Comment by alirezat775** [comment]
Yes, I tried force resolution strategy but not working :((
I suggest using `api` for exposing the library instead of `compile`. if set `api` for okhttp other apps
can decide using which version of okhttp

**Comment by charbgr** [comment]
Hi @alirezat775,

Unfortunately Square removed `HttpEngine` class in OkHttp version 3.4.0 and thats why you get this error. So the current version of`SeismicInterceptor` is currently incompatible with OkHttp version 3.4.0 and above.

I bumped the version and fix the error but I cannot promise you when I will publish the artifact because I had some issues with maven lately. The fix is available on `master`.

I will keep you updated !
